[filetype]
prepend_rules = [
  { url = ".*", fg = "darkgray", dim = true },
  { url = "**/.*", fg = "darkgray", dim = true },
]

[icon]
prepend_globs = [
  { url = "**/.*", text = "󰘓", fg = "darkgray" },
]
